name: sharelove
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^7.0.0
  flutter_sequence_animation: "^1.0.1"
  shared_preferences: "^0.4.2"
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
   - assets/empty.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
#     - family: Assistant
#       fonts:
#         - asset: fonts/Assistant-Regular.ttf
# #        - asset: fonts/Assistant-Light.ttf
#     - family: Raleway
#       fonts:
# #        - asset: fonts/Raleway-ExtraLight.ttf
# #       - asset: fonts/Raleway-Light.ttf
#         - asset: fonts/Raleway-Regular.ttf
# #        - asset: fonts/Raleway-Thin.ttf
    - family: Dosis
      fonts:
#        - asset: fonts/Assistant-Regular.ttf
#        - asset: fonts/Dosis-ExtraLight.ttf
#       - asset: fonts/Dosis-Light.ttf
        - asset: fonts/Dosis-Regular.ttf
#     - family: Roboto
#       fonts:
#         - asset: fonts/Roboto-Medium.ttf
# #        - asset: fonts/Roboto-Thin.ttf
# #        - asset: fonts/Roboto-Light.ttf
# #        - asset: fonts/Roboto-Regular.ttf
#     - family: SourceSansPro
#       fonts:
# #        - asset: fonts/SourceSansPro-Light.ttf
# #        - asset: fonts/SourceSansPro-ExtraLight.ttf
#        - asset: fonts/SourceSansPro-Regular.ttf
#     - family: TitilliumWeb
#       fonts:
# #        - asset: fonts/TitilliumWeb-Light.ttf
# #        - asset: fonts/TitilliumWeb-ExtraLight.ttf
#         - asset: fonts/SourceSansPro-Regular.ttf
#     - family: WorkSans
#       fonts:
# #        - asset: fonts/WorkSans-Medium.ttf
# #        - asset: fonts/WorkSans-Thin.ttf
# #        - asset: fonts/WorkSans-Light.ttf
#         - asset: fonts/WorkSans-Regular.ttf
#     - family: AmaticSC
#       fonts:
#         - asset: fonts/AmaticSC-Regular.ttf